### ISSUE TITLE
4 things that could improve your code

### ISSUE THREAD

**Issue by JoarHansson** [OsborneLinus/openAPI-map#1]
General:

Code comments: 
The code has no comments. I think it would be easier to understand in general  how the app works if you added some comments here and there!

Repo structure:
Maybe a bit unclear what the roles of folders basic-map/ and geolocation/ are in the repo. The app lives in routing/ as I understand it(?). Some comments about the repo (readme.md) would probably help to clarify.

Some CSS stuff:
* The map overflows on both axes in the browser window. 100vw/vh on #myMap could be changed to 100% and make the body 100vw/vh instead.
* Maybe add some margin/padding between the elements (map and form, form and window edges), for visual purposes.

**Comment by OsborneLinus** [comment]
Thanks for the input!
